# 74 维 PPG 单周期特征定义 (extract_ppg_features_from_single_ppg_cycle)
# 索引 i 对应 ppg_single_cycle_features[i]；x=采样点索引, y=PPG幅值, fs=900Hz
# valley_left/valley_right=左右波谷, peak=波峰, a/b/e=apg波峰,
# inflection=重搏切迹, deriv=一阶导数, apg=二阶导数
FEATURES_74 = {
 0:  "ppg_duration           周期总时长 (s) = (valley_right-valley_left)/fs",
 1:  "ppg_duration_sys       收缩期时长 = (peak-valley_left)/fs",
 2:  "ppg_duration_dias      舒张期时长 = (valley_right-peak)/fs",
 3:  "ppg_duration_ratio_sys 收缩期占比 = duration_sys/duration",
 4:  "ratio_derivpeak_peak   (deriv_peak-valley_left)/(peak-valley_left)",
 5:  "ppg_duration_ratio_dn  (e_pos-valley_left)/duration",
 6:  "apg_ratio_a_peak       (a_pos-valley_left)/(peak-valley_left)",
 7:  "apg_ratio_a2b_peak     (b_pos-a_pos)/(peak-valley_left)",
 8:  "apg_ratio_e2i_e2v      (inflection_pos-e_pos)/(valley_right-e_pos)",
 9:  "ppg_width_sys@0.1      幅值>=0.1*peak 的收缩期宽度(s)",
 10: "ppg_width_sys@0.25     幅值>=0.25*peak 的收缩期宽度(s)",
 11: "ppg_width_sys@0.33     幅值>=0.33*peak 的收缩期宽度(s)",
 12: "ppg_width_sys@0.5      幅值>=0.5*peak  的收缩期宽度(s)",
 13: "ppg_width_sys@0.66     幅值>=0.66*peak 的收缩期宽度(s)",
 14: "ppg_width_sys@0.75     幅值>=0.75*peak 的收缩期宽度(s)",
 15: "ppg_width_dias@0.1     幅值>=0.1*peak 的舒张期宽度(s)",
 16: "ppg_width_dias@0.25    ...",
 17: "ppg_width_dias@0.33    ...",
 18: "ppg_width_dias@0.5     ...",
 19: "ppg_width_dias@0.66    ...",
 20: "ppg_width_dias@0.75    ...",
 21: "deriv_width@0.25       一阶导数 >=0.25*峰 的总宽度(s)",
 22: "ppg_area_sys           收缩期面积 (trapz)",
 23: "ppg_area_dias          舒张期面积 (trapz)",
 24: "ppg_area               sys+dias 总面积",
 25: "ppg_area_maxslope_left  valley_left~deriv_peak 面积",
 26: "ppg_area_maxslope_right deriv_peak~peak 面积",
 27: "ppg_area_dn_left       peak~e_pos 面积",
 28: "ppg_area_dn_right      e_pos~valley_right 面积",
 29: "ppg_area_ratio_dn      dn_right/(maxslope_left+maxslope_right+dn_left)",
 30: "ppg_slope_sys_avg      收缩期平均斜率 mean(deriv[valley_left:peak])",
 31: "ppg_slope_dias_avg     舒张期平均斜率 mean(deriv[peak:valley_right])",
 32: "ppg_slope_sys          (y[peak]-y[valley_left])/(x[peak]-x[valley_left])",
 33: "ppg_slope_dias         (y[valley_right]-y[peak])/(x[valley_right]-x[peak])",
 34: "ppg_slope_max          deriv[deriv_peak] (最大上升斜率)",
 35: "ppg_curv               e_pos 处曲率 calc_curvature(apg,deriv)",
 36: "apg_amp_a              apg[a_pos]",
 37: "apg_amp_b              apg[b_pos]",
 38: "apg_amp_e              apg[e_pos]",
 39: "apg_amp_ratio_b_a     apg[b]/apg[a]",
 40: "apg_amp_ratio_e_a     apg[e]/apg[a]",
 41: "apg_amp_agi           ratio_b_a - ratio_e_a",
 42: "ppg_amp_ai            y[inflection]/y[peak]  (AI 幅度比)",
 43: "ppg_duration_delta_t  (inflection-peak)/fs",
 44: "ppg_duration_ratio_dt delta_t/duration",
 45: "deriv_width@0.75      一阶导数 >=0.75*峰 宽度",
 46: "deriv_left_width@0.33 valley_left~0.33宽 左段宽度",
 47: "deriv_left_width@0.66 ...",
 48: "deriv_right_width@0.33 peak 侧 0.33 宽右段",
 49: "deriv_right_width@0.66 ...",
 50: "ppg_deriv_area_pos_left  valley_left~deriv_peak 导数正面积",
 51: "ppg_deriv_area_pos_right deriv_peak~peak 导数正面积",
 52: "ppg_deriv_area_peak2dn   peak~e_pos 导数负面积",
 53: "ppg_slope_sys_a2derivpeak a_pos~deriv_peak 平均斜率",
 54: "ppg_slope_sys_derivpeak2b deriv_peak~b_pos 平均斜率",
 55: "ppg_slope_dias_peak2dn    peak~e_pos 平均斜率",
 56: "ppg_slope_dias_inflection deriv[inflection]",
 57: "ppg_slope_ratio_inflection_derivpeak deriv[inflection]/slope_max",
 58: "ppg_width_sys@0.33_extended  (扩展归一化)",
 59: "ppg_width_sys@0.66_extended  ...",
 60: "ppg_width_dias@0.33_extended ...",
 61: "ppg_width_dias@0.66_extended ...",
 62: "deriv_left_width@0.33_extended ...",
 63: "deriv_left_width@0.66_extended ...",
 64: "deriv_right_width@0.33_extended ...",
 65: "deriv_right_width@0.66_extended ...",
 66: "ppg_usdc_mean_top20  上侧对称性 usdc 前20%均值",
 67: "ppg_usdc_median       usdc 中位数",
 68: "ppg_usdc_mean_tail20  usdc 后20%均值",
 69: "ppg_usdc_std          usdc 标准差",
 70: "ppg_dsdc_mean_top20   下侧对称性 dsdc 前20%均值",
 71: "ppg_dsdc_median       dsdc 中位数",
 72: "ppg_dsdc_mean_tail20  dsdc 后20%均值",
 73: "ppg_dsdc_std          dsdc 标准差",
}
# 注意: extract_ppg_features 在组窗特征时删除了部分索引:
#   window 特征删除: [70,71,67,57,56,6,8,37,38,39,40,41,66,68,69,52]
#   (即最终进入模型的窗口特征约 74-16 = 58 维，再按各模型 features.txt 选子集)
